pipeline:
  projectIdentifier: shemer_test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: shemer_github
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        template:
          templateRef: org.Golden_CI_Build_Template
          versionLabel: v1
          templateInputs:
            type: CI
            variables:
              - name: k8sConnectorRef
                type: String
                value: k8s_cluster
              - name: buildNamespace
                type: String
                value: harness-delegate-ng
              - name: buildServiceAccountName
                type: String
                value: shemer-delegate
              - name: dockerConnectorRef
                type: String
                value: ahemer_ghcr
              - name: imageRepository
                type: String
                value: ghcr.io/shemreader/coderabbit-test
    - stage:
        name: update gitops manifest
        identifier: update_gitops_manifest
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_cluster
              namespace: harness-delegate-ng
              serviceAccountName: shemer-delegate
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Update GitOps Manifest
                  identifier: updateGitOpsManifest
                  spec:
                    shell: Sh
                    image: alpine/git
                    connectorRef: account.Docker_Hub_Public
                    envVariables:
                      GITHUB_TOKEN: <+secrets.getValue("github_pat")>
                    command: |-
                      set -e
                      sed -i "s#^\(\s*tag:\s*\).*#\1\"<+pipeline.sequenceId>\"#" k8s/values.yaml
                      git config user.email "ci@harness.io"
                      git config user.name "Harness CI"
                      git add k8s/values.yaml
                      git commit -m "ci: bump emp-api image to <+pipeline.sequenceId> [skip ci]" || echo "no changes to commit"
                      git push "https://x-access-token:${GITHUB_TOKEN}@github.com/shemreader/coderabbit-test.git" HEAD:main
  identifier: test_pipeline
  name: test pipeline
