pipeline:
  projectIdentifier: shemer_test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: shemer_github
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        template:
          templateRef: Golden_CI_Build_Template
          versionLabel: v1
    - stage:
        name: security scan
        identifier: security_scan
        description: ""
        template:
          templateRef: Golden_Security_Scan_Template
          versionLabel: v1
    - stage:
        name: deploy to dev
        identifier: deploy_to_dev
        description: ""
        template:
          templateRef: Golden_K8s_Deploy_Template
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: emp_api
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: coderabbittest
              environment:
                environmentRef: dev
                infrastructureDefinitions:
                  - identifier: k8s_dev
              execution:
                steps:
                  - step:
                      identifier: health_check
                      type: Http
                      spec:
                        url: http://emp-api.<+infra.namespace>.svc.cluster.local/health
    - stage:
        name: deploy to pre-prod
        identifier: deploy_to_pre_prod
        description: ""
        template:
          templateRef: Golden_K8s_Deploy_Template
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: emp_api
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: coderabbittest
              environment:
                environmentRef: pre_prod
                infrastructureDefinitions:
                  - identifier: k8s_pre_prod
              execution:
                steps:
                  - step:
                      identifier: health_check
                      type: Http
                      spec:
                        url: http://emp-api.<+infra.namespace>.svc.cluster.local/health
    - stage:
        name: production approval
        identifier: production_approval
        description: ""
        template:
          templateRef: Golden_Approval_Template
          versionLabel: v1
    - stage:
        name: deploy to production
        identifier: deploy_to_production
        description: ""
        template:
          templateRef: Golden_K8s_Deploy_Template
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: emp_api
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: coderabbittest
              environment:
                environmentRef: prod
                infrastructureDefinitions:
                  - identifier: k8s_prod
              execution:
                steps:
                  - step:
                      identifier: health_check
                      type: Http
                      spec:
                        url: http://emp-api.<+infra.namespace>.svc.cluster.local/health
  identifier: test_pipeline
  name: test pipeline
